### ISSUE TITLE
Model init won't run

### ISSUE THREAD

**Issue by mhmdreda99** [EFeru/bldc-motor-control-FOC#2]
hello  Emanuel i want to use your model and the model init give me this error with a missing file and i have a question can i mdify this work to be able two run on another hub motor with a 17inch 48v and 1500 watt rated power ? thanks for help [
![Capture](https://user-images.githubusercontent.com/49542070/131885452-d41d10ef-63c9-4173-ae86-2d7fbbe5ff0f.PNG)
](url) 
Edit: i edit the motor parameters in model init and then it ran successful  and i ran the simulink model i get this result in figure and it seems all wrong  can you please guide me with steps to be able to match this model with my motor specs : 
![Capture](https://user-images.githubusercontent.com/49542070/131887651-4edfe987-3735-47a8-8ca2-cb5eef22feb6.PNG)

**Comment by EFeru** [comment]
I'm not sure why it can't find that file because it's located in https://github.com/EmanuelFeru/bldc-motor-control-FOC/blob/master/01_Libraries/02_Plant/BLDCmotorControl_data.mat
You can try to double click on it to see if it can be loaded.

About the simulation, it does not look that great. Try with default plant parameters in the file above and see if it's working correctly and then update the parameters to your motor.

**Comment by mhmdreda99** [comment]
thanks for reply but i want to ask if that i could configure that model to a two hub motors with rated power 1500 watt and 48 V and 17inch diameter ?
  if yes could you please tell me the main parameters that i should consider ?

**Comment by EFeru** [comment]
Yes, your should be able to do that by changing the plant parameters. The plant is the bldc motor (one motor, if the other motor is similar simulating one motor only is sufficient)

**Comment by mhmdreda99** [comment]
i will try to do that thanks bro and if i grt an output i will pull a request and join contributors
