### ISSUE TITLE
extern P rtP_Left missing in latest generated code?

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [EFeru/bldc-motor-control-FOC#3]
Hi,

I just updated our firmware with your newest foc model code export and it seems like BLDC_controller_data.c doesnt declare `extern P    rtP_Left;` anymore?

was this intenionally?

**Comment by EFeru** [comment]
Hi, this repo contains the raw generated files and there is no `extern` here. Do you mean this one?
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/bd4a34dabf655ba8a9a48e9974ebb0b619796fde/Src/util.c#L81

Because i don't remember having  `extern` in BLDC_controller_data.c

**Comment by 0xFEEDC0DE64** [comment]
Yes, but the generated .c files provided that symbol. In the latest revision the symbol went missing. If you update the .h and .c files in your foc firmware you should experience the same linker errors :)

**Comment by EFeru** [comment]
The FOC firmware/repo is already updated with this latest generated files and it compiles successfully.

**Comment by 0xFEEDC0DE64** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/master/Src/BLDC_controller_data.c
and
https://github.com/EFeru/bldc-motor-control-FOC/blob/master/BLDC_controller_ert_rtw/BLDC_controller_data.c

are not idendical, the one from the bldc-motor-control-FOC repo is missing the needed rtP_Left

**Comment by EFeru** [comment]
Correct, that is because in the raw generated files (this repo) the parameters rtP are in main.c file defined as static:
https://github.com/EFeru/bldc-motor-control-FOC/blob/master/BLDC_controller_ert_rtw/ert_main.c

While in the FOC repo the parameters are moved to BLDC_controller_data.c and renamed to accommodate the handling of Left and Right parameters. This is the only "manual" thing that needs to be done to make the generated files work in the FOC repo.

**Comment by Maik93** [comment]
Hi @EFeru, thanks for your effort in this project.
Is there any script or patch file that can help on the conversion of the C-generated simulink code of this repo to the hoverboard's version?
